### ISSUE TITLE
Proper Use With PHPStan?

### ISSUE THREAD

**Issue by andrewjmead** [thephpleague/uri-src#107]
| Q       | A     |
|---------|-------|
| Package | league/uri |
| Version | 6.8.0 |

### Question

Hey League!

I'm using `league/uri` in a project with PHPStan and PHPStan seems unable to detect classes such as `League\Uri\UriTemplate` or `League\Uri\Uri`. This was happening in a large project, but I put together a minimal example here:

https://github.com/andrewjmead/phpstan-league-uri-issue

This runs PHPStan against some source code which is copied directly from the `thephpleague/uri`. There PHPStan error is:

```
------ --------------------------------------------------------------------- 
  Line   index.php                                                            
 ------ --------------------------------------------------------------------- 
  20     Instantiated class League\Uri\UriTemplate not found.                 
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
```

Any ideas as to what's going on here? I tried adding extra discovery into the PHPStan config, but nothing seemed to help PHPStan detect those classes. I wasn't sure if this was a known thing (though I couldn't find any docs about it).

I wasn't running into this issue with any other composer packages which is why I figured it best to ask here. I'm not sure if there's something special about `league/uri` that requires additional configuration in `phpstan.neon`.

**Comment by nyamsprod** [comment]
@andrewjmead While your question has nothing to do with the package on itself a quick look at your application `composer` and `phpstan` config file shows that you are trying to install a PHP8.1+ package on a PHP7.3 installation which does not work at least that is what I could understand.

**Comment by andrewjmead** [comment]
🤦‍♂️

Thanks for taking a look. I was trying to use PHPStan to target the version my WordPress plugin targets. That's the issue. Much appreciated and thanks for you time. Just sent a one-time sponsorship.
