### ISSUE TITLE
PSR-7 v2

### ISSUE THREAD

**Issue by kelunik** [thephpleague/uri-src#108]
### Feature Request

Support for PSR-7 v2 in league/uri-components.

See https://www.php-fig.org/psr/psr-7/meta/#72-type-additions

**Comment by nyamsprod** [comment]
@kelunik I indeed saw that PSR-7 v2 was out. The question that I have is does it warrant an new version for all packages to correctly implements the return type or not ? 

If so I could take the opportunity to bump correctly all repo and to have a clean release with all repo moving to v7. it might take a bit more time but the result would be worthwhile I think

**Comment by kelunik** [comment]
Adding parameter types requires a new major version for packages shipping implementations, yes.

So the plan is bumping everything to v7 so the next version for `league/uri-components` will be `7.0.0`?

**Comment by nyamsprod** [comment]
Yes that's the plan so that tags can be added on the monorepo directly. Makes management easier for me

**Comment by nyamsprod** [comment]
@kelunik turns out that moving to PSR-7 is a lot easier than I thought since the package is already fully typed but I will have to wait for the https://github.com/php-http/psr7-integration-tests package to supports:

- [PSR-7 version 2](https://github.com/php-http/psr7-integration-tests/pull/68)
- [PHPUnit 10](https://github.com/php-http/psr7-integration-tests/pull/60)

**Comment by nyamsprod** [comment]
The master branch now supports PSR-7 version two. 

- [ ] Still need to make sure all the dependencies are respected.
- [ ] Still need to update the documentation for v7

**Comment by nyamsprod** [comment]
@kelunik most of the work to release version 7 is done

Updating the documentation is still a to do work but it will be an easy one as most of the public API is still the same. 

I have a question for you as a user of the package though. I want to remove the `create` prefix from all the named constructor so in

```diff
- public static createFromString(Stringable|string $uri): self
+ public static fromString(Stringable|string $uri): self
```

It can be done in 2 ways:
- either I do a hard BC break or
- I keep the deprecated version at least in v7. 

I presume the latter is better as it allows for a simpler migration path to v7 🤔 Another possibility is to think that renaming is not necessary. 

I am just looking for feedback to see what's the best scenario (from the POV of maintenance burden). IMHO at some point the `create` prefix ought to be removed... the sooner the better, unless I am missing something

**Comment by nyamsprod** [comment]
The `createFrom*` family of named constructor will be deprecatede in version 7 and remove in the next major version. So only thing missing now is documentation update

**Comment by kelunik** [comment]
@nyamsprod Sorry, forgot to answer. It's best to deprecate and introduce aliases if you want to transition to the new naming.

**Comment by trowski** [comment]
I updated a branch of `http-server` this morning, [`http-server@3.x-league-7.x`](https://github.com/amphp/http-server/tree/3.x-league-7.x), to give the `7.x-dev` a try. Everything works without any code modifications. Retaining the old names as deprecated should allow us to support 6.x and 7.x.

**Comment by nyamsprod** [comment]
```
league/uri:7.0.0-beta.2
league/uri-components:7.0.0-beta.2
league/uri-interfaces:7.0.0-beta.2
```

are tagged.

Unless some big bug are found if all goes well the new stable tag will be released next week 🤞🏾
