### ISSUE TITLE
add compatibility for psr/http-message 2.0 version

### ISSUE THREAD

**Issue by monta990** [thephpleague/uri-src#111]
### Feature Request

| Q           | A      |
|-------------|--------|
| Package     | yes    |
| New Feature | yes    |
| BC Break    | ??? |

#### Proposal

add compatibility for psr/http-message 2.0 version

**Comment by nyamsprod** [comment]
@monta990 there's already work in progress for that see PR #110

**Comment by stof** [comment]
@nyamsprod it would have been better to have a version supporting both 1.1 and 2.0 of the interface to make it easier to avoid dependency hell with packages wanting incompatible versions of the interfaces.
This might probably even be possible as a 6.9.0 release.

**Comment by stof** [comment]
and this dependency hell becomes even worse when considering that the new version supporting 2.0 (and only 2.0) is a new major version of the package.

**Comment by nyamsprod** [comment]
@stof thanks for the heads up I updated the dependencies to support `^1.1.0` since it does not break the current code I am ok with the change as it improve migration path.

**Comment by stof** [comment]
great. Thanks
