### ISSUE TITLE
Getting the filesystem path from a file URI

### ISSUE THREAD

**Issue by stof** [thephpleague/uri-src#124]
### Feature Request

| Q           | A      |
|-------------|--------|
| Package     | yes    |
| New Feature | yes    |
| BC Break    | no |

#### Proposal

The package currently exposes `Uri::fromWindowsPath` and `Uri::fromUnixPath` encapsulating the logic to create a `file://` URI from a path to support all cases.
It would be great to have a utility exposing the opposite operation.

**Comment by nyamsprod** [comment]
Might be something to add to the `BaseUri` class perhaps 🤔

**Comment by nyamsprod** [comment]
@stof I opened a PR to resolve your feature request ... let me know if the intended behaviour is OK for you. reviews and comments are welcomed. 😉

**Comment by nyamsprod** [comment]
As of 7.6.0 still not release but present in the master branch the `toWindowsPath` and `toUnixPath` are now also present in the `Uri` class
