### ISSUE TITLE
Factory method to create a data uri from a string content

### ISSUE THREAD

**Issue by stof** [thephpleague/uri-src#126]
### Feature Request

| Q           | A      |
|-------------|--------|
| Package     | yes    |
| New Feature | yes    |
| BC Break    | no |

#### Proposal

Currently, we have `Uri::fromFileContents` to create a data URI from the content of a file. However, there is nothing to create a data URI representing a string we have in PHP already. Having to write a temporary file for that does not seem handy.

Also, it would be nice if this factory could generate URIs that don't use base64 encoding but instead apply percent encoding on the content, as this allows to keep the URI shorter in case few URI special characters are used (base 64 implies a 33% increase in length).

The mimetype would be provided as an argument to the function.

**Comment by stof** [comment]
`fromDataUriString` looks confusing to me as method name. When reading `Uri::fromDataUriString($a)`, it gives me the impression that `$a` would have to contain a data uri as a string.
However I admit I don't have a better name for now (I tried to find a good name for that but I failed)

**Comment by nyamsprod** [comment]
let's remove confusion ... `Uri::fromData` should be better and a bit shorter

**Comment by stof** [comment]
Regarding `$parameters`, I'm wondering whether it should be provided as a string or as `array<string, string>` so that the method performs the necessary URL encoding. As my own use case for parameters would be `charset=utf-8`, I'm fine either way (this case does not require any special encoding). I haven't investigated to see whether Modifier has helper to add those parameters though.
I'm totally fine with relying on `Modifier::dataPathToBinary` to provide the base64 encoding instead of supporting it directly (anyway, my own use case wants to avoid base 64).

`Uri::fromData` indeed looks nicer as name. Good job.

**Comment by nyamsprod** [comment]
that one was faster to resolve 😄
