### ISSUE TITLE
Class "League\Uri\UriString" not found in League\Uri\Uri::new()

### ISSUE THREAD

**Issue by rudolfbyker** [thephpleague/uri-src#129]
### Bug Report

_(Fill in the relevant information below to help triage your issue.)_

| Information | Description |
|-------------|-------------|
| Package     | league/uri  |
| Version     | 7.0.0       |
| PHP version | 8.1.13      |
| OS Platform | Linux x64   |

#### Summary

```
Error: Class "League\Uri\UriString" not found in League\Uri\Uri::new() (line 426 of /vv/vendor/league/uri/Uri.php). 
```

when calling

```
League\Uri\Uri::createFromString('https://vv1.astro:8080/auth')
```

#### Standalone code, or other way to reproduce the problem

```
<?php
\League\Uri\Uri::createFromString('https://vv1.astro:8080/auth');
```

#### Expected result

No error.

#### Actual result

Error.

**Comment by nyamsprod** [comment]
@rudolfbyker thanks for reporting the bug did your try with the most recent version since many fixes have landed since the release of 7.0.0

**Comment by nyamsprod** [comment]
@rudolfbyker I have install via composer league\uri:7.0.0 but I fail to get the same error has you did ? Did you use composer to install the package ? 🤔

**Comment by rudolfbyker** [comment]
Yes, I used composer. Also, I can't update to 7.3.0 yet because of conflicting dependencies with my current version of Drupal. I have downgraded to ^6 for now, which works. I'll try to make a minimal example repo next week.

**Comment by nyamsprod** [comment]
@rudolfbyker to me this seems to be an issue with your dependencies too. V7 requires Téo other packages. If one is missing or not up to date then your will indeed get the error you had. I suspect this has to do with your version of 'uri-interfaces'.

**Comment by rudolfbyker** [comment]
I see now that for some reason, I'm getting `uri-interfaces` version `7.0.0-beta2` instead of `7.0.0`.

```
astro:/vv# composer update -W
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 4 updates, 0 removals
...
  - Upgrading league/uri (6.8.0 => 7.0.0)
  - Upgrading league/uri-interfaces (2.3.0 => 7.0.0-beta.2)
...
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 4 updates, 0 removals
...
  - Upgrading league/uri-interfaces (2.3.0 => 7.0.0-beta.2): Extracting archive
  - Upgrading league/uri (6.8.0 => 7.0.0): Extracting archive
...
astro:/vv# composer why league/uri-interfaces
league/uri 7.0.0 requires league/uri-interfaces (^7.0) 
```

Trying to figure out why I'm not getting `7.0.0`:

```
astro:/vv# composer why-not league/uri-interfaces 7.0.0
league/uri-interfaces   7.0.0      requires         psr/http-message (^1.1 || ^2.0)           
rscdevelopers/vv_drupal dev-master does not require psr/http-message (but 1.0.1 is installed) 
Not finding what you were looking for? Try calling `composer update "league/uri-interfaces:7.0.0" --dry-run` to get another view on the problem.

astro:/vv# composer why-not psr/http-message 1.1
drupal/core-recommended 9.5.11 requires psr/http-message (~1.0.1) 
Not finding what you were looking for? Try calling `composer update "psr/http-message:1.1" --dry-run` to get another view on the problem.
```

So Drupal core `9.5.11` is simply not compatible with `league/uri-interfaces 7.0.0` because of its strict dependency on `psr/http-message ~1.0.1`.

**Comment by nyamsprod** [comment]
@rudolfbyker sorry for the dependency issue. Nice finding at least how you were able to find it. 

On a side note I do not understand why Drupal would block to `1.0.1` since most of the v1 dependency on PSR-7 moved to `1.1.0` 🤔  maybe something to ask the Drupal core to look into.
