### ISSUE TITLE
`Query::createFromUri()` deprecation: typo in upgrade docs?

### ISSUE THREAD

**Issue by davidrans** [thephpleague/uri-src#134]
### Bug Report

https://github.com/thephpleague/uri-src/blob/9407477016a93963bbc8ddaf4161f8bd4f9839f6/docs/components/7.0/upgrading.md?plain=1#L143

Should this be `Query::createFromUri() -> Query::fromUri()`?

**Comment by nyamsprod** [comment]
indeed it is a typo you can provide a PR with the correct info I will gladly review it and merge it.

**Comment by davidrans** [comment]
Done! https://github.com/thephpleague/uri-src/pull/136
