### ISSUE TITLE
Difference between `Query::new()` and `Query::fromVariable([])`

### ISSUE THREAD

**Issue by davidrans** [thephpleague/uri-src#135]
### Bug Report

_(Fill in the relevant information below to help triage your issue.)_

| Information | Description |
|-------------|-------------|
| Package     | uri-components |
| Version     | 7.4.1 |
| PHP version | 8.3.2 |
| OS Platform | Linux |

#### Summary
```php
> $q = League\Uri\Components\Query::new()            
= League\Uri\Components\Query {#5499}                
                                                     
> $q->getUriComponent()                              
= ""                                                 
                                                     
> $q2 = League\Uri\Components\Query::fromVariable([])
= League\Uri\Components\Query {#5528}                
                                                     
> $q2->getUriComponent()                             
= "?"                                                
```

#### Expected result

I would expect `getUriComponent()` to return `""` in both cases

#### Actual result

`League\Uri\Components\Query::fromVariable([])->getUriComponent()` returns `"?"`

**Comment by nyamsprod** [comment]
Well I see where this reasoning comes from but PHP behaviour is at "fault" on this one.
`Query::fromVariable` output depends on `http_build_query` behaviour whereas `Query::new` does not.

```php
<?php
var_dump(http_build_query([])); // returns ''
```

`http_build_query` never returns `null` (aka the absence of query), it returns the empty string instead, while `Query::new()` by default returns `null`.

Hope this clarify the output.

**Comment by davidrans** [comment]
Along the same line:
```php
> $u = League\Uri\Http::new('http://abc.com?a=1')              
= League\Uri\Http {#5714}                                      
                                                               
> $q = League\Uri\Components\Query::fromVariable([])           
= League\Uri\Components\Query {#5525}                          
                                                               
> League\Uri\Modifier::from($u)->mergeQuery($q)->getUriString()
= "http://abc.com?a=1&"

**Comment by nyamsprod** [comment]
No It should not. Doing so would break expectation. You should interchangeably use fromVariable and http_build_query. Both work with array like in your example but also with objects which is a less documented feature with has an even more "strange" behaviour. 
IMHO fromVariable should be used when migrating from http_build_query to proper query usage and creation.

**Comment by davidrans** [comment]
Gotcha, maybe I just misunderstood the purpose of that function. The [upgrade docs](https://uri.thephpleague.com/components/7.0/upgrading/) say to replace `Query::createFromParams` with `Query::fromParameters`, but I looked and that function is also deprecated and references `fromVariable`:

https://github.com/thephpleague/uri-components/blob/b94fe4097885f1b51c4c3fcb78025fbbabbb5d9d/Components/Query.php#L662

Is there a replacement for `createFromParams`/`fromParameters` that maintains similar behavior?

**Comment by nyamsprod** [comment]
createFromParams/createFromParameters are indeed replaced by fromVariable because of an issue in the methods design for more information check the following issue https://github.com/thephpleague/uri-src/issues/123

**Comment by davidrans** [comment]
I appreciate the clarification :+1:

I'll just update the places I construct `Query`s to something like:
```php
if ($params) {
   $q = Query::fromVariable($params);
} else {
   $q = Query::new();
}
```
